enum EOrigin {
    "Timed Drop",
    "Achievement",
    "Purchased",
    "Traded",
    "Crafted",
    "Store Promotion",
    "Gifted",
    "Support Granted",
    "Found in Crate",
    "Earned",
    "Third-Party Promotion",
    "Wrapped Gift",
    "Halloween Drop",
    "Steam Purchase",
    "Foreign Item",
    "CD Key",
    "Collection Reward",
    "Preview Item",
    "Steam Workshop Contribution",
    "Periodic score reward",
    "MvM Badge completion reward",
    "MvM Squad surplus reward",
    "Recipe output",
    "Quest Drop",
    "Quest Loaner Item",
    "Trade-Up",
    "Viral Competitive Beta Pass Spread",
    "CYOA Blood Money Purchase",
    "War Paint",
    "Untradable Free Contract Reward",
};

export default EOrigin;
